In [1]:
import matplotlib
#matplotlib.use('Agg')
%matplotlib tk
import matplotlib.pyplot as plt

%autosave 180

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import numpy as np

from utility_match_units import (binary_reader_waveforms,match_units,
                                 search_spikes_parallel, load_ks2_spikes,
                                 reload_ks2_templates, Match_to_ground_truth,
                                 plot_single_unit,
                                plot_single_unit_parallel)

clrs = ['blue', 'red', 'green', 'cyan',
'black','grey','brown','slategrey','darkviolet','darkmagenta',
'orange','firebrick','lawngreen','dodgerblue','crimson','orchid','slateblue',
'darkgreen','darkorange','indianred','darkviolet','deepskyblue','greenyellow',
'peru','cadetblue','forestgreen','slategrey','lightsteelblue','rebeccapurple',
'darkmagenta','yellow','hotpink']

import multiprocessing

n_cpus = multiprocessing.cpu_count()//2

Autosaving every 180 seconds


In [2]:
# dataset aprameters:
root_dir = '/media/cat/4TBSSD/data/synthetic/run13/'
n_channels = 384
n_times = 101

# convert KS2 spike trains to 2 column standard and reorder spikes by sequential index
if False:
    prefix = "KS2"
    spike_train_sorted = load_ks2_spikes(root_dir, n_channels, n_times)
    #print ("Spike train: \n", spike_train_sorted)
    # remake templates from data
    print ("Remaking templates ")
    data_type='int16'
    templates_sorted = reload_ks2_templates(root_dir, spike_train_sorted, data_type, 
                                            n_channels, n_times)
    print ("templates sorted: ", templates_sorted.shape)

else:
    prefix = "YASS2"
    spike_train_sorted = np.load(root_dir+'/spike_train.npy')
    spike_train_sorted[:,0]-=n_times//2
    templates_sorted = np.load(root_dir+'/templates.npy')



In [3]:
# match to ground truth data;
matcher = Match_to_ground_truth(root_dir, 
                                spike_train_sorted, 
                                templates_sorted,
                                n_cpus)
print (" DONE MATCHING ")


 ground truth templates:  (100, 101, 384)
searching match unit:  0
# spikes in sorted unit:  2888
# matches:  17
searching match unit:  1
# spikes in sorted unit:  1494
# matches:  8
searching match unit:  2
# spikes in sorted unit:  2244
# matches:  16
searching match unit:  3
# spikes in sorted unit:  932
# matches:  8
searching match unit:  4
# spikes in sorted unit:  1973
# matches:  9
searching match unit:  5
# spikes in sorted unit:  863
# matches:  3
searching match unit:  6
# spikes in sorted unit:  1753
# matches:  9
searching match unit:  7
# spikes in sorted unit:  2456
# matches:  14
searching match unit:  8
# spikes in sorted unit:  2514
# matches:  8
searching match unit:  9
# spikes in sorted unit:  2601
# matches:  16
searching match unit:  10
# spikes in sorted unit:  915
# matches:  8
searching match unit:  11
# spikes in sorted unit:  927
# matches:  2
searching match unit:  12
# spikes in sorted unit:  552
# matches:  1
searching match unit:  13
# spikes in sorted u

# matches:  33
searching match unit:  17
# spikes in sorted unit:  1021
# matches:  13
searching match unit:  18
# spikes in sorted unit:  2179
# matches:  20
searching match unit:  19
# spikes in sorted unit:  571
# matches:  7
searching match unit:  20
# spikes in sorted unit:  793
# matches:  9
searching match unit:  21
# spikes in sorted unit:  1744
# matches:  17
searching match unit:  22
# spikes in sorted unit:  2955
# matches:  24
searching match unit:  23
# spikes in sorted unit:  2929
# matches:  41
searching match unit:  24
# spikes in sorted unit:  2724
# matches:  27
searching match unit:  25
# spikes in sorted unit:  842
# matches:  7
searching match unit:  26
# spikes in sorted unit:  1599
# matches:  16
searching match unit:  27
# spikes in sorted unit:  1708
# matches:  16
searching match unit:  28
# spikes in sorted unit:  917
# matches:  11
searching match unit:  29
# spikes in sorted unit:  1404
# matches:  14
searching match unit:  30
# spikes in sorted unit:  777


In [4]:
# load matched data
#matcher.load_matches('/match_to_sort/')
matcher.load_matches('/match_to_truth/')
print ("n_units: ", len(matcher.n_spikes))


n_units:  100


In [5]:
# Make Pie Charts from results;
n_matches = 3
matcher.make_pie_charts(n_matches)
    

n matches:  3
sizes: [1655   23   23]  , clrs:  ['blue', 'red', 'green']
sizes: [2247   38   27]  , clrs:  ['blue', 'red', 'green']
sizes: [1613   20   20]  , clrs:  ['blue', 'red', 'green']
sizes: [1663   24   23]  , clrs:  ['blue', 'red', 'green']
sizes: [2332   32   30]  , clrs:  ['blue', 'red', 'green']
sizes: [1665   35   29]  , clrs:  ['blue', 'red', 'green']
sizes: [2522   35   31]  , clrs:  ['blue', 'red', 'green']
sizes: [2347   35   33]  , clrs:  ['blue', 'red', 'green']
sizes: [1491   20   19]  , clrs:  ['blue', 'red', 'green']
sizes: [2041   33   22]  , clrs:  ['blue', 'red', 'green']
sizes: [1867   25   23]  , clrs:  ['blue', 'red', 'green']
sizes: [311  61   7]  , clrs:  ['blue', 'red', 'green']
sizes: [2117   35   33]  , clrs:  ['blue', 'red', 'green']
sizes: [2062   27   26]  , clrs:  ['blue', 'red', 'green']
sizes: [552  13   9]  , clrs:  ['blue', 'red', 'green']
sizes: [488   8   8]  , clrs:  ['blue', 'red', 'green']
sizes: [2321   33   28]  , clrs:  ['blue', 'red', '

IndexError: index 98 is out of bounds for axis 0 with size 98

In [6]:
# make violin plots
#matcher.load_matches('/match_to_sort/')
#matcher.load_matches('/match_to_truth/')
print ("n_units: ", len(matcher.n_spikes))

def get_violin_data(matcher, 
                    selected_unit,
                    root_dir):
    
    n_matches2 = 1
    
    #spike_train_gt = np.load(root_dir + 'ground_truth/spike_train_ground_truth.npy')
    #templates_sorted = np.load(root_dir + 'templates_reloaded_good.npy')
    spike_train_sorted = matcher.spike_train_sorted
    templates_sorted = matcher.templates_sorted
    spike_train_gt = matcher.spike_train_gt
    templates_gt = matcher.templates_gt
        
    max_chans_sorted = templates_sorted.ptp(1).argmax(1)

    # fix n-chans and sample rate for computations below
    n_chans = templates_sorted.shape[2]
    sample_rate = 30000
    
    # load units
    #matcher = Match_to_ground_truth(root_dir, spike_train_sorted, templates_sorted)

    matched_units = np.array(matcher.ids_matched[selected_unit][1])
    #print ("matched_units: ", matched_units)

    # count # of spikes in each matching unit;
    n_spk = []
    for k in range(len(matcher.matched_spikes_array[selected_unit])):
        n_spk.append(len(matcher.matched_spikes_array[selected_unit][k]))
    
    # select top 5 matching units by size and plot them;
    n_spk = np.hstack(n_spk)
    idx_sorted = np.argsort(n_spk)[::-1][:n_matches2]

    # ****************** GROUND TRUTH UNIT COMPUTATION ***************
    # load spikes for ground truth unit:
    idx = np.where(spike_train_gt[:,1]==selected_unit)[0]
    spk_gt = spike_train_gt[idx,0]
    tot_spikes_gt = spk_gt.shape[0]
    
    # count # of spikes in each matching unit;
    n_spk = []
    for p in range(len(matcher.matched_spikes_array[selected_unit])):
        n_spk.append(len(matcher.matched_spikes_array[selected_unit][p]))

    # select top match unit by size <-- MIGHT NEED TWEAKING
    # SHOULD SELECT TOP MATCH BY PURITY or COMPLETENESS
    n_matches2 = 1
    n_spk = np.hstack(n_spk)
    idx_sorted = np.argsort(n_spk)[::-1][:n_matches2]

    # ************ SCATTER PLOT BEST X MATCHES **************
    # track TP rates; 
    TP_rate = []
    # look only at the best match:
    #for k in range(len(ptps_sorted)):
    #for k in range(len(idx_sorted)):
    k=0   
    size = np.sort(matcher.venn_array[selected_unit])[::-1][k]
    tot_spikes = matcher.n_spikes_array[selected_unit]  # spikes in the ground truth unit
    tp_rate = size/float(tot_spikes)   

    id_ = idx_sorted[k]
    print ("Selected_unit: ", selected_unit, " , matching id: ", id_)

    # compute purity and compleness
    n_spikes_sorted_unit = np.where(matcher.spike_train_sorted[:,1]==
                      matched_units[id_])[0].shape[0]

    purity = size/float(n_spikes_sorted_unit)*100.
    completeness = size/float(tot_spikes)*100.


    TP_rate = tp_rate
                
    #for k in range(n_matches2):
    k=0
    idx_gt = np.where(matcher.spike_train_gt[:,1]==selected_unit)[0]
    times_gt = matcher.spike_train_gt[idx_gt,0]

    idx_sort = np.where(matcher.spike_train_sorted[:,1]==matched_units[idx_sorted[k]])[0]
    times_sort = matcher.spike_train_sorted[idx_sort,0]

    vintersect = n_spk[idx_sorted][k]
    v1 = times_gt.shape[0] - vintersect
    v2 = times_sort.shape[0] - vintersect

    FP_rate = v2/float(times_sort.shape[0])
        
    return TP_rate, FP_rate, purity, completeness, id_

# reload original spike trains
print ("RELOADING DATA AGAINST TRUTH")
matcher.load_data(spike_train_sorted, templates_sorted)
matcher.load_matches('/match_to_truth/')

TP=[]
FP=[]
purity = []
completeness = []
matching_ids = []
for selected_unit in range(len(matcher.n_spikes)):

    TP_, FP_, purity_, completeness_, id_ = get_violin_data(matcher,
                                                       selected_unit,
                                                       root_dir)

    TP.append(TP_)
    FP.append(FP_)
    purity.append(purity_)
    completeness.append(completeness_)
    matching_ids.append(id_)

# reload matches for all units
print ("RELOADING DATA AGAINST SORT")
matcher.load_data(spike_train_sorted, templates_sorted)
matcher.load_matches('/match_to_sort/')

spike_train_sorted = matcher.spike_train_gt.copy()
templates_sorted = matcher.templates_gt.copy()
spike_train_gt = matcher.spike_train_sorted.copy()
templates_gt = matcher.templates_sorted.copy()

matcher.spike_train_gt = spike_train_gt
matcher.templates_gt = templates_gt
matcher.spike_train_sorted = spike_train_sorted
matcher.templates_sorted = templates_sorted
   
TP_all=[]
FP_all=[]
purity_all = []
completeness_all = []
matching_ids_all = []
for selected_unit in range(len(matcher.n_spikes)):
    
    TP_, FP_, purity_, completeness_, id_ = get_violin_data(matcher,
                                                       selected_unit,
                                                       root_dir)

    TP_all.append(TP_)
    FP_all.append(FP_)
    purity_all.append(purity_)
    completeness_all.append(completeness_)
    matching_ids_all.append(id_)


n_units:  100
RELOADING DATA AGAINST TRUTH
Selected_unit:  0  , matching id:  49
Selected_unit:  1  , matching id:  2
Selected_unit:  2  , matching id:  64
Selected_unit:  3  , matching id:  31
Selected_unit:  4  , matching id:  90
Selected_unit:  5  , matching id:  71
Selected_unit:  6  , matching id:  85
Selected_unit:  7  , matching id:  29
Selected_unit:  8  , matching id:  91
Selected_unit:  9  , matching id:  24
Selected_unit:  10  , matching id:  77
Selected_unit:  11  , matching id:  90
Selected_unit:  12  , matching id:  25
Selected_unit:  13  , matching id:  84
Selected_unit:  14  , matching id:  12
Selected_unit:  15  , matching id:  65
Selected_unit:  16  , matching id:  56
Selected_unit:  17  , matching id:  47
Selected_unit:  18  , matching id:  48
Selected_unit:  19  , matching id:  27
Selected_unit:  20  , matching id:  78
Selected_unit:  21  , matching id:  6
Selected_unit:  22  , matching id:  73
Selected_unit:  23  , matching id:  19
Selected_unit:  24  , matching id

In [7]:
print (len(matching_ids), np.unique(matching_ids).shape)
print (len(matching_ids_all), np.unique(matching_ids_all).shape)

print (purity)

100 (98,)
98 (98,)
[100.1209921355112, 100.13368983957218, 98.2338611449452, 100.12040939193257, 88.2664647993944, 98.87173396674585, 100.11909487892021, 100.08528784648188, 95.76107899807322, 100.24557956777996, 100.0, 11.771385314155943, 99.71738106453132, 100.09708737864078, 100.0, 98.58585858585859, 99.52830188679245, 100.0984251968504, 100.13824884792626, 100.0, 32.80796350062215, 99.25841414717627, 99.9659979598776, 99.93145990404386, 100.11074197120709, 99.17355371900827, 99.87445072190835, 99.88290398126463, 100.21857923497268, 100.21443888491778, 97.97724399494311, 67.1505599336375, 100.19221528111484, 100.12214983713355, 100.12936610608021, 98.49424269264836, 99.13793103448276, 99.9231950844854, 99.84794728839331, 100.08093889113718, 100.0, 99.71671388101983, 100.0, 100.07256894049348, 100.0, 100.0, 99.89258861439313, 99.81718464351006, 99.49452401010952, 98.33531510107015, 99.6298010180472, 100.0, 99.47368421052632, 99.41250524548889, 100.07578628268283, 99.01408450704226, 9

In [8]:
# plot violin plots
import matplotlib.patches as mpatches

print (TP)
TP_out = np.array(TP)*100.
FP_out = np.array(FP)*100.

#fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(6, 6))
fig = plt.figure()
ax=plt.subplot(2,1,1)
#plt.plot(purity)
#plt.show()

data = [purity, completeness, TP_out, FP_out]
clrs=['black','blue','red','green']
labels=['purity', 'completeness', 'true pos', 'false pos']

# plot KS2 best matches
for k in range(4):
    violin_parts = ax.violinplot(data[k], [k], points=20, widths=1.0,
                      showmeans=True, showextrema=True, showmedians=True)

    #y = np.histogram(data[k],bins=np.arange(0,105,10))
    #plt.plot(y[1][:-1],y[0])

    plt.title(labels[k])
ax.set_ylim(0,100)
ax.set_xticks([])
ax.set_title(prefix+" best matches against ground truth", fontsize=20)

# ************************************************
# plot KS2 all units
TP_out = np.array(TP_all)*100.
FP_out = np.array(FP_all)*100.
data = [purity_all, completeness_all, TP_out, FP_out]
ax=plt.subplot(2,1,2)
for k in range(4):
    violin_parts = ax.violinplot(data[k], [k], points=20, widths=1.0,
                      showmeans=True, showextrema=True, showmedians=True)

    #y = np.histogram(data[k],bins=np.arange(0,110,10))
    #plt.plot(y[1][:-1],y[0])

    
ax.set_ylim(0,100)
ax.set_xticks(np.arange(0,4,1))
ax.set_xticklabels(labels, fontsize=20)
ax.set_title(prefix+" all units against ground truth", fontsize=20)


plt.suptitle(prefix+" run on static data;   Injected units "+str(len(purity))+" # of sorted units: "+str(len(purity_all)), fontsize=20)
#plt.suptitle("YASS2 run on static data", fontsize=20)
plt.show()

[0.9987929993964997, 0.9986666666666667, 0.9932266009852216, 0.9987987987987988, 0.9982876712328768, 0.9776864357017029, 0.997626582278481, 0.9991485738612176, 0.9966577540106952, 0.9980440097799511, 0.9994646680942184, 0.8474114441416893, 0.9971738106453132, 0.9980638915779284, 1.0, 1.0, 0.9931536157466838, 0.9960822722820764, 0.997246443322625, 1.0, 0.9974779319041615, 0.9977064220183486, 0.9949238578680203, 0.99556162512803, 0.9955947136563876, 0.997624703087886, 0.9949968730456535, 0.9988290398126464, 1.0, 0.9985754985754985, 0.9974259974259975, 0.9963076923076923, 0.9985632183908046, 0.998375964271214, 1.0, 0.9937444146559428, 0.9982638888888888, 0.9984650805832693, 0.9989858012170385, 0.9995957962813258, 0.9906351791530945, 0.9971671388101983, 1.0, 0.9992753623188406, 0.9986979166666666, 0.9986833443054641, 0.9941207910208445, 0.9909255898366606, 0.9957841483979764, 0.9939903846153846, 0.9907961343764381, 1.0, 0.9989429175475687, 0.9924591537494764, 0.9977332829618436, 1.0, 0.997

In [13]:
print (len(matching_ids), np.unique(matching_ids).shape)
print (len(matching_ids_all), np.unique(matching_ids_all).shape)


100 (98,)
98 (98,)


In [1]:
# save
scale_amplitude = 10.
n_matches = 3
save_fig = True
# plot ptp of spikes from different units:
# selected_unit = 15 #15 #47 #39 #21

# don't run without Agg matplotlib backend
units = np.unique(matcher.spike_train_gt[:,1])
n_cores = 4
if False:
     plot_single_unit_parallel(units, 
                               root_dir,
                               spike_train_sorted, 
                               n_matches, clrs, scale_amplitude,
                               save_fig,
                               n_cores)
else:
    for selected_unit in units: 
        plot_single_unit(root_dir, selected_unit, matcher, 
                  n_matches, clrs, scale_amplitude,
                  save_fig)

NameError: name 'np' is not defined

In [ ]:
print (len(ptp_gt_unit), len(purity),len(completeness))
print (ptp_gt_unit)
print (purity)
ax=plt.subplot(121)
plt.scatter(ptp_gt_unit, purity, c='blue')
plt.title("True Positive Rate \n(# spikes found / # spikes injected)", fontsize=15)
plt.xlabel("PTP of unit", fontsize=20)
plt.xlim(left=0)
plt.ylim(0,1.05)
ax.tick_params(axis='both', which='major', labelsize=20)

# plot purity
ax=plt.subplot(122)
ax.tick_params(axis='both', which='major', labelsize=20)
plt.scatter(ptp_gt_unit,completeness, c='red')
plt.title("Purity \n(# spikes found / # spikes in unit)", fontsize=15)
plt.xlabel("PTP of injected unit", fontsize=20)
plt.xlim(left=0)
plt.ylim(0,1.05)
plt.suptitle("Neuropixels Drift Simulation run3\n shifts: "+
             str(np.array([-0.1,  -0.05,  0.,    0.05])*40)+" um"+ " @ "+
             str(np.array([0.,  6000000., 12000000., 18000000.])/30000)+ " sec"+
            "\n10mins recording, 384 channels"+
            "\n Sorted using KS2")
plt.show()

In [ ]:
t1 = np.load('/media/cat/1TB/data/synthetic/run3/ground_truth/templates_ground_truth.npy')
print (t1.shape)
t2 = np.load('/media/cat/1TB/data/synthetic/run3/templates_reloaded_good.npy')
print (t2.shape)

max1 = t1[2].ptp(0).argmax(0)
max2 = t2[50].ptp(0).argmax(0)
print (max1, max2)

ax=plt.subplot(121)
plt.plot(t1[2],c='black')
ax=plt.subplot(122)
plt.plot(t2[50]/10.,c='blue')
plt.show()


In [ ]:
d1 = max_chans_sorted
d2 = max_chans_unit
t1, t2, t3 = np.intersect1d(d1,d2,return_indices=True)
print (t1,t2,t3)

t1 = np.where(np.in1d(d1, d2))[0]
print (t1)



In [67]:
spike_train = np.load('/media/cat/1TB/data/synthetic/run3/ground_truth/spike_train_ground_truth.npy')
print (spike_train)
templates = np.load('/media/cat/1TB/data/synthetic/run3/ground_truth/templates_ground_truth.npy')
print (templates.shape)

units = np.load('/media/cat/1TB/data/synthetic/run3/ground_truth/units.npy')
print (units)

ctr=0
spike_train_corrected = spike_train.copy()
for unit in units:
    idx = np.where(spike_train[:,1]==unit)[0]
    spike_train_corrected[idx,1]=ctr
    ctr+=1
    
print (spike_train_corrected)
np.save('/media/cat/1TB/data/synthetic/run3/ground_truth/spike_train_ground_truth_corrected.npy',spike_train_corrected)

[[      35      420]
 [    6119      420]
 [   12204      420]
 ...
 [17983395      247]
 [17990820      247]
 [17998245      247]]
(49, 101, 384)
[420 339 421 348 473 418  62 362 565 239 498 474 324 298 471 441 417 443
 356 424  63 437 485 160 156 302 346 334 431 486  66 204  14 258 300  16
 150  52 317 277 184 456  65 481  38 436 558 194 247]
[[      35        0]
 [    6119        0]
 [   12204        0]
 ...
 [17983395       48]
 [17990820       48]
 [17998245       48]]


In [21]:
units=np.arange(5)
units = [good_units[3]]

for unit in units:
    fig = plt.figure()
    ax = plt.subplot(131)
    #plt.plot(templates[unit].T)
    plt.plot(wfs_array[unit].mean(0))

    ax = plt.subplot(132)
    #spikes = spikes[idx]
    spikes = times[unit]
    print ("spikes:", spikes.shape, "ptps: ", ptps[unit].shape)
    plt.scatter(spikes/30000., ptps[unit])

    ax=plt.subplot(133)
    max_chan = wfs_array[unit].mean(0).ptp(0).argmax(0)#templates[unit].ptp(0).argmax(0)
    print (wfs_array[unit].shape)

    cmap = cm.get_cmap('viridis',wfs_array[unit].shape[0])
    clrs = cmap(np.arange(wfs_array[unit].shape[0]))
    print (clrs)
    for k in range(0,wfs_array[unit].shape[0],10):
        plt.plot(wfs_array[unit][k].T,c=cmap(k))


plt.show()



spikes: (8210,) ptps:  (8210,)
(8210, 101)
[[0.267004 0.004874 0.329415 1.      ]
 [0.267004 0.004874 0.329415 1.      ]
 [0.267004 0.004874 0.329415 1.      ]
 ...
 [0.993248 0.906157 0.143936 1.      ]
 [0.993248 0.906157 0.143936 1.      ]
 [0.993248 0.906157 0.143936 1.      ]]


In [9]:
fname = '/home/cat/Downloads/yass/samples/10chan/phy/whitening_mat.npy'

n_channels = 10

whitening_mat = np.random.rand(n_channels,n_channels)

np.save(fname, whitening_mat)
print (whitening_mat.shape)
print (whitening_mat)

(10, 10)
[[0.61659694 0.20125714 0.48515898 0.45059603 0.89409843 0.8158124
  0.30200264 0.06808628 0.60955651 0.7760584 ]
 [0.19814057 0.21134196 0.27791917 0.52312241 0.20263871 0.21097603
  0.34816364 0.1852993  0.90506002 0.80562087]
 [0.970196   0.70466193 0.08746122 0.33371635 0.44791585 0.00678562
  0.41421277 0.65443008 0.8541354  0.41522301]
 [0.88052786 0.34072116 0.12298287 0.23288985 0.98943396 0.56546028
  0.38736253 0.87851743 0.83882004 0.96018176]
 [0.5622632  0.19456103 0.89831444 0.56587043 0.12599613 0.24817026
  0.47188959 0.55809954 0.72628178 0.72821972]
 [0.59236306 0.06332327 0.35662913 0.93425548 0.15622572 0.77164442
  0.62013196 0.67339586 0.97380542 0.9211003 ]
 [0.55011567 0.22242238 0.41892959 0.23396425 0.80036351 0.00612786
  0.72244072 0.1119026  0.84247935 0.13666388]
 [0.1674969  0.17014984 0.70297569 0.28534628 0.87704159 0.62894665
  0.38268201 0.47207143 0.53495952 0.46683818]
 [0.58624526 0.67612232 0.60880662 0.66169478 0.10866143 0.88197916
  0.

In [24]:
max_chans = templates.ptp(1).argmax(1)
ptps = templates.ptp(1).max(1)
ptps_all = templates.ptp(1)
print (ptps_all.shape)

print (max_chans)
print (ptps)


(426, 364)
[  0   1   1   1   2   3   4   6   7   5  10  13  14  14  15  16  17  18
  20  21  30  26  29  29  30  31  32  35  37  41  42  43  45  46  49  50
  38  56  58  60  69  68  68  68  72  70  71  74  75  76 342  80  79  80
  80  83  82  84 333  85  86  87  88  88  88  88  89  89  90  88  87  92
 336  94  95  98  99  84 101 103 104 108 109 109 111 111 111 112 114 115
 119 119 120 121 125 127 127 124 131 133 134 134 132 140 137 138 140 332
 140 140 141 142 142 140 143 145 146 147 147 149 149 149 149 150 284 149
 154 154 154 162 164 165 166 164 169 170 173 173 174 177 178 173 180 181
 182 186 182 185 185 186 186 189 190 192 194 197 198 199 201 204 204 206
 208 208 209 209 213 209 210 212 205 209 213 213 213 213 216 216 216 217
 219 220 226 228 229 229 229 230 230 233 235 215 236 236 238 239 239 242
 245 245 248 248 248 248 249 249 252 252 253 253 262 262 262 262 262 262
 262 262 262 262 262 262 252 265 265 265 266 266 257 268 268 253 273 273
 274 277 277 277 280 262 280 282 280 284

In [33]:
# plot scatter vs. depth
fig=plt.figure()
ax=plt.subplot(111)
for k in range(426):
    idx = np.where(spike_clusters==k)[0]
    times = spike_times[idx]/30000.
    plt.scatter(times, times*0+geom[max_chans[k],1]+(np.random.rand()*80-40),s=1, alpha=.9)
    
ax.tick_params(axis = 'both', which = 'major', labelsize = 20)
plt.ylim(3800,-100)
plt.xlim(-10,times[-1]+10)
plt.ylabel("Depth (um)",fontsize=20)
plt.xlabel("Time (sec)",fontsize=20)

plt.show()



In [59]:
import wavefile

data = wavefile.loadWave('/home/cat/Downloads/time code signal.wav')

print (data[1].shape)

plt.plot(data[1].squeeze()[:1000])
plt.show()

(1, 200000)


In [70]:
datas = data[1].squeeze()
print (datas.shape)
print (datas)

(200000,)
[ 0.5  0.5  0.5 ... -0.5 -0.5 -0.5]


In [74]:
idx = np.where(datas>0)[0]
print (idx)
diffs = idx[1:]-idx[:-1]
print (diffs)

[     0      1      2 ... 199992 199993 199994]
[1 1 1 ... 1 1 1]


In [75]:
start = []
end = []
start.append(0)
for k in range(1, diffs.shape[0]-1, 1):
    if (diffs[k]-diffs[k-1])>1:
        end.append(k-1)
        start.append(k)
end.append(k)
end = np.array(end)
start = np.array(start)
print ((end-start)[:100])
diffs_redone = end-start+1
print (diffs_redone)

[ 7 10  8  9  9  9  9  9  9  9  9  9  9  9  4  9  9  9  9  9  9  9  9  9
  9  9  9  9  9  9  9  9  9  9  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9
  9  9  9  9  9  9  9  9  9  4  4  4  4  4  4  4  4  4  4  4  4  4  9  4
  9  9  9  9]
[ 8 11  9 ...  5  5  4]


In [79]:
ax=plt.subplot(111)
sample_rate = 20000.
hist = np.histogram(diffs_redone, np.arange(-20,50,1))
plt.bar(hist[1][:-1]/sample_rate,hist[0],0.9/sample_rate)
plt.xlabel("Inter pulse interval (seconds)")
plt.title("Distribution of inter-spike-interval (20 sec wav file provided by Avisoft)")
#ax.set_yscale('log')
plt.show()